/* Generated at libc build time from kernel syscall list.  */

#ifndef _SYSCALL_H
# error "Never use <bits/syscall.h> directly; include <sys/syscall.h> instead."
#endif

#include <sgidefs.h>
#if _MIPS_SIM == _ABIN32
# ifdef __NR_N32_open
#  define SYS_Linux __NR_N32_Linux
#  define SYS_Linux_syscalls __NR_N32_Linux_syscalls
#  define SYS__newselect __NR_N32__newselect
#  define SYS__sysctl __NR_N32__sysctl
#  define SYS_accept __NR_N32_accept
#  define SYS_access __NR_N32_access
#  define SYS_acct __NR_N32_acct
#  define SYS_add_key __NR_N32_add_key
#  define SYS_adjtimex __NR_N32_adjtimex
#  define SYS_afs_syscall __NR_N32_afs_syscall
#  define SYS_alarm __NR_N32_alarm
#  define SYS_bind __NR_N32_bind
#  define SYS_brk __NR_N32_brk
#  define SYS_cachectl __NR_N32_cachectl
#  define SYS_cacheflush __NR_N32_cacheflush
#  define SYS_capget __NR_N32_capget
#  define SYS_capset __NR_N32_capset
#  define SYS_chdir __NR_N32_chdir
#  define SYS_chmod __NR_N32_chmod
#  define SYS_chown __NR_N32_chown
#  define SYS_chroot __NR_N32_chroot
#  define SYS_clock_getres __NR_N32_clock_getres
#  define SYS_clock_gettime __NR_N32_clock_gettime
#  define SYS_clock_nanosleep __NR_N32_clock_nanosleep
#  define SYS_clock_settime __NR_N32_clock_settime
#  define SYS_clone __NR_N32_clone
#  define SYS_close __NR_N32_close
#  define SYS_connect __NR_N32_connect
#  define SYS_creat __NR_N32_creat
#  define SYS_create_module __NR_N32_create_module
#  define SYS_delete_module __NR_N32_delete_module
#  define SYS_dup __NR_N32_dup
#  define SYS_dup2 __NR_N32_dup2
#  define SYS_epoll_create __NR_N32_epoll_create
#  define SYS_epoll_ctl __NR_N32_epoll_ctl
#  define SYS_epoll_wait __NR_N32_epoll_wait
#  define SYS_execve __NR_N32_execve
#  define SYS_exit __NR_N32_exit
#  define SYS_exit_group __NR_N32_exit_group
#  define SYS_fadvise64 __NR_N32_fadvise64
#  define SYS_fchdir __NR_N32_fchdir
#  define SYS_fchmod __NR_N32_fchmod
#  define SYS_fchown __NR_N32_fchown
#  define SYS_fcntl __NR_N32_fcntl
#  define SYS_fcntl64 __NR_N32_fcntl64
#  define SYS_fdatasync __NR_N32_fdatasync
#  define SYS_fgetxattr __NR_N32_fgetxattr
#  define SYS_flistxattr __NR_N32_flistxattr
#  define SYS_flock __NR_N32_flock
#  define SYS_fork __NR_N32_fork
#  define SYS_fremovexattr __NR_N32_fremovexattr
#  define SYS_fsetxattr __NR_N32_fsetxattr
#  define SYS_fstat __NR_N32_fstat
#  define SYS_fstatfs __NR_N32_fstatfs
#  define SYS_fstatfs64 __NR_N32_fstatfs64
#  define SYS_fsync __NR_N32_fsync
#  define SYS_ftruncate __NR_N32_ftruncate
#  define SYS_futex __NR_N32_futex
#  define SYS_get_kernel_syms __NR_N32_get_kernel_syms
#  define SYS_get_mempolicy __NR_N32_get_mempolicy
#  define SYS_getcwd __NR_N32_getcwd
#  define SYS_getdents __NR_N32_getdents
#  define SYS_getegid __NR_N32_getegid
#  define SYS_geteuid __NR_N32_geteuid
#  define SYS_getgid __NR_N32_getgid
#  define SYS_getgroups __NR_N32_getgroups
#  define SYS_getitimer __NR_N32_getitimer
#  define SYS_getpeername __NR_N32_getpeername
#  define SYS_getpgid __NR_N32_getpgid
#  define SYS_getpgrp __NR_N32_getpgrp
#  define SYS_getpid __NR_N32_getpid
#  define SYS_getpmsg __NR_N32_getpmsg
#  define SYS_getppid __NR_N32_getppid
#  define SYS_getpriority __NR_N32_getpriority
#  define SYS_getresgid __NR_N32_getresgid
#  define SYS_getresuid __NR_N32_getresuid
#  define SYS_getrlimit __NR_N32_getrlimit
#  define SYS_getrusage __NR_N32_getrusage
#  define SYS_getsid __NR_N32_getsid
#  define SYS_getsockname __NR_N32_getsockname
#  define SYS_getsockopt __NR_N32_getsockopt
#  define SYS_gettid __NR_N32_gettid
#  define SYS_gettimeofday __NR_N32_gettimeofday
#  define SYS_getuid __NR_N32_getuid
#  define SYS_getxattr __NR_N32_getxattr
#  define SYS_init_module __NR_N32_init_module
#  define SYS_io_cancel __NR_N32_io_cancel
#  define SYS_io_destroy __NR_N32_io_destroy
#  define SYS_io_getevents __NR_N32_io_getevents
#  define SYS_io_setup __NR_N32_io_setup
#  define SYS_io_submit __NR_N32_io_submit
#  define SYS_ioctl __NR_N32_ioctl
#  define SYS_keyctl __NR_N32_keyctl
#  define SYS_kill __NR_N32_kill
#  define SYS_lchown __NR_N32_lchown
#  define SYS_lgetxattr __NR_N32_lgetxattr
#  define SYS_link __NR_N32_link
#  define SYS_listen __NR_N32_listen
#  define SYS_listxattr __NR_N32_listxattr
#  define SYS_llistxattr __NR_N32_llistxattr
#  define SYS_lookup_dcookie __NR_N32_lookup_dcookie
#  define SYS_lremovexattr __NR_N32_lremovexattr
#  define SYS_lseek __NR_N32_lseek
#  define SYS_lsetxattr __NR_N32_lsetxattr
#  define SYS_lstat __NR_N32_lstat
#  define SYS_madvise __NR_N32_madvise
#  define SYS_mbind __NR_N32_mbind
#  define SYS_mincore __NR_N32_mincore
#  define SYS_mkdir __NR_N32_mkdir
#  define SYS_mknod __NR_N32_mknod
#  define SYS_mlock __NR_N32_mlock
#  define SYS_mlockall __NR_N32_mlockall
#  define SYS_mmap __NR_N32_mmap
#  define SYS_mount __NR_N32_mount
#  define SYS_mprotect __NR_N32_mprotect
#  define SYS_mq_getsetattr __NR_N32_mq_getsetattr
#  define SYS_mq_notify __NR_N32_mq_notify
#  define SYS_mq_open __NR_N32_mq_open
#  define SYS_mq_timedreceive __NR_N32_mq_timedreceive
#  define SYS_mq_timedsend __NR_N32_mq_timedsend
#  define SYS_mq_unlink __NR_N32_mq_unlink
#  define SYS_mremap __NR_N32_mremap
#  define SYS_msgctl __NR_N32_msgctl
#  define SYS_msgget __NR_N32_msgget
#  define SYS_msgrcv __NR_N32_msgrcv
#  define SYS_msgsnd __NR_N32_msgsnd
#  define SYS_msync __NR_N32_msync
#  define SYS_munlock __NR_N32_munlock
#  define SYS_munlockall __NR_N32_munlockall
#  define SYS_munmap __NR_N32_munmap
#  define SYS_nanosleep __NR_N32_nanosleep
#  define SYS_nfsservctl __NR_N32_nfsservctl
#  define SYS_open __NR_N32_open
#  define SYS_pause __NR_N32_pause
#  define SYS_personality __NR_N32_personality
#  define SYS_pipe __NR_N32_pipe
#  define SYS_pivot_root __NR_N32_pivot_root
#  define SYS_poll __NR_N32_poll
#  define SYS_prctl __NR_N32_prctl
#  define SYS_pread64 __NR_N32_pread64
#  define SYS_ptrace __NR_N32_ptrace
#  define SYS_putpmsg __NR_N32_putpmsg
#  define SYS_pwrite64 __NR_N32_pwrite64
#  define SYS_query_module __NR_N32_query_module
#  define SYS_quotactl __NR_N32_quotactl
#  define SYS_read __NR_N32_read
#  define SYS_readahead __NR_N32_readahead
#  define SYS_readlink __NR_N32_readlink
#  define SYS_readv __NR_N32_readv
#  define SYS_reboot __NR_N32_reboot
#  define SYS_recvfrom __NR_N32_recvfrom
#  define SYS_recvmsg __NR_N32_recvmsg
#  define SYS_remap_file_pages __NR_N32_remap_file_pages
#  define SYS_removexattr __NR_N32_removexattr
#  define SYS_rename __NR_N32_rename
#  define SYS_request_key __NR_N32_request_key
#  define SYS_reserved177 __NR_N32_reserved177
#  define SYS_reserved193 __NR_N32_reserved193
#  define SYS_restart_syscall __NR_N32_restart_syscall
#  define SYS_rmdir __NR_N32_rmdir
#  define SYS_rt_sigaction __NR_N32_rt_sigaction
#  define SYS_rt_sigpending __NR_N32_rt_sigpending
#  define SYS_rt_sigprocmask __NR_N32_rt_sigprocmask
#  define SYS_rt_sigqueueinfo __NR_N32_rt_sigqueueinfo
#  define SYS_rt_sigreturn __NR_N32_rt_sigreturn
#  define SYS_rt_sigsuspend __NR_N32_rt_sigsuspend
#  define SYS_rt_sigtimedwait __NR_N32_rt_sigtimedwait
#  define SYS_sched_get_priority_max __NR_N32_sched_get_priority_max
#  define SYS_sched_get_priority_min __NR_N32_sched_get_priority_min
#  define SYS_sched_getaffinity __NR_N32_sched_getaffinity
#  define SYS_sched_getparam __NR_N32_sched_getparam
#  define SYS_sched_getscheduler __NR_N32_sched_getscheduler
#  define SYS_sched_rr_get_interval __NR_N32_sched_rr_get_interval
#  define SYS_sched_setaffinity __NR_N32_sched_setaffinity
#  define SYS_sched_setparam __NR_N32_sched_setparam
#  define SYS_sched_setscheduler __NR_N32_sched_setscheduler
#  define SYS_sched_yield __NR_N32_sched_yield
#  define SYS_semctl __NR_N32_semctl
#  define SYS_semget __NR_N32_semget
#  define SYS_semop __NR_N32_semop
#  define SYS_semtimedop __NR_N32_semtimedop
#  define SYS_sendfile __NR_N32_sendfile
#  define SYS_sendfile64 __NR_N32_sendfile64
#  define SYS_sendmsg __NR_N32_sendmsg
#  define SYS_sendto __NR_N32_sendto
#  define SYS_set_mempolicy __NR_N32_set_mempolicy
#  define SYS_set_tid_address __NR_N32_set_tid_address
#  define SYS_setdomainname __NR_N32_setdomainname
#  define SYS_setfsgid __NR_N32_setfsgid
#  define SYS_setfsuid __NR_N32_setfsuid
#  define SYS_setgid __NR_N32_setgid
#  define SYS_setgroups __NR_N32_setgroups
#  define SYS_sethostname __NR_N32_sethostname
#  define SYS_setitimer __NR_N32_setitimer
#  define SYS_setpgid __NR_N32_setpgid
#  define SYS_setpriority __NR_N32_setpriority
#  define SYS_setregid __NR_N32_setregid
#  define SYS_setresgid __NR_N32_setresgid
#  define SYS_setresuid __NR_N32_setresuid
#  define SYS_setreuid __NR_N32_setreuid
#  define SYS_setrlimit __NR_N32_setrlimit
#  define SYS_setsid __NR_N32_setsid
#  define SYS_setsockopt __NR_N32_setsockopt
#  define SYS_settimeofday __NR_N32_settimeofday
#  define SYS_setuid __NR_N32_setuid
#  define SYS_setxattr __NR_N32_setxattr
#  define SYS_shmat __NR_N32_shmat
#  define SYS_shmctl __NR_N32_shmctl
#  define SYS_shmdt __NR_N32_shmdt
#  define SYS_shmget __NR_N32_shmget
#  define SYS_shutdown __NR_N32_shutdown
#  define SYS_sigaltstack __NR_N32_sigaltstack
#  define SYS_socket __NR_N32_socket
#  define SYS_socketpair __NR_N32_socketpair
#  define SYS_stat __NR_N32_stat
#  define SYS_statfs __NR_N32_statfs
#  define SYS_statfs64 __NR_N32_statfs64
#  define SYS_swapoff __NR_N32_swapoff
#  define SYS_swapon __NR_N32_swapon
#  define SYS_symlink __NR_N32_symlink
#  define SYS_sync __NR_N32_sync
#  define SYS_sysfs __NR_N32_sysfs
#  define SYS_sysinfo __NR_N32_sysinfo
#  define SYS_syslog __NR_N32_syslog
#  define SYS_sysmips __NR_N32_sysmips
#  define SYS_tgkill __NR_N32_tgkill
#  define SYS_timer_create __NR_N32_timer_create
#  define SYS_timer_delete __NR_N32_timer_delete
#  define SYS_timer_getoverrun __NR_N32_timer_getoverrun
#  define SYS_timer_gettime __NR_N32_timer_gettime
#  define SYS_timer_settime __NR_N32_timer_settime
#  define SYS_times __NR_N32_times
#  define SYS_tkill __NR_N32_tkill
#  define SYS_truncate __NR_N32_truncate
#  define SYS_umask __NR_N32_umask
#  define SYS_umount2 __NR_N32_umount2
#  define SYS_uname __NR_N32_uname
#  define SYS_unlink __NR_N32_unlink
#  define SYS_ustat __NR_N32_ustat
#  define SYS_utime __NR_N32_utime
#  define SYS_utimes __NR_N32_utimes
#  define SYS_vhangup __NR_N32_vhangup
#  define SYS_vserver __NR_N32_vserver
#  define SYS_wait4 __NR_N32_wait4
#  define SYS_waitid __NR_N32_waitid
#  define SYS_write __NR_N32_write
#  define SYS_writev __NR_N32_writev
# else
#  define SYS_Linux __NR_Linux
#  define SYS_Linux_syscalls __NR_Linux_syscalls
#  define SYS__newselect __NR__newselect
#  define SYS__sysctl __NR__sysctl
#  define SYS_accept __NR_accept
#  define SYS_access __NR_access
#  define SYS_acct __NR_acct
#  define SYS_add_key __NR_add_key
#  define SYS_adjtimex __NR_adjtimex
#  define SYS_afs_syscall __NR_afs_syscall
#  define SYS_alarm __NR_alarm
#  define SYS_bind __NR_bind
#  define SYS_brk __NR_brk
#  define SYS_cachectl __NR_cachectl
#  define SYS_cacheflush __NR_cacheflush
#  define SYS_capget __NR_capget
#  define SYS_capset __NR_capset
#  define SYS_chdir __NR_chdir
#  define SYS_chmod __NR_chmod
#  define SYS_chown __NR_chown
#  define SYS_chroot __NR_chroot
#  define SYS_clock_getres __NR_clock_getres
#  define SYS_clock_gettime __NR_clock_gettime
#  define SYS_clock_nanosleep __NR_clock_nanosleep
#  define SYS_clock_settime __NR_clock_settime
#  define SYS_clone __NR_clone
#  define SYS_close __NR_close
#  define SYS_connect __NR_connect
#  define SYS_creat __NR_creat
#  define SYS_create_module __NR_create_module
#  define SYS_delete_module __NR_delete_module
#  define SYS_dup __NR_dup
#  define SYS_dup2 __NR_dup2
#  define SYS_epoll_create __NR_epoll_create
#  define SYS_epoll_ctl __NR_epoll_ctl
#  define SYS_epoll_wait __NR_epoll_wait
#  define SYS_execve __NR_execve
#  define SYS_exit __NR_exit
#  define SYS_exit_group __NR_exit_group
#  define SYS_fadvise64 __NR_fadvise64
#  define SYS_fchdir __NR_fchdir
#  define SYS_fchmod __NR_fchmod
#  define SYS_fchown __NR_fchown
#  define SYS_fcntl __NR_fcntl
#  define SYS_fcntl64 __NR_fcntl64
#  define SYS_fdatasync __NR_fdatasync
#  define SYS_fgetxattr __NR_fgetxattr
#  define SYS_flistxattr __NR_flistxattr
#  define SYS_flock __NR_flock
#  define SYS_fork __NR_fork
#  define SYS_fremovexattr __NR_fremovexattr
#  define SYS_fsetxattr __NR_fsetxattr
#  define SYS_fstat __NR_fstat
#  define SYS_fstatfs __NR_fstatfs
#  define SYS_fstatfs64 __NR_fstatfs64
#  define SYS_fsync __NR_fsync
#  define SYS_ftruncate __NR_ftruncate
#  define SYS_futex __NR_futex
#  define SYS_get_kernel_syms __NR_get_kernel_syms
#  define SYS_get_mempolicy __NR_get_mempolicy
#  define SYS_getcwd __NR_getcwd
#  define SYS_getdents __NR_getdents
#  define SYS_getegid __NR_getegid
#  define SYS_geteuid __NR_geteuid
#  define SYS_getgid __NR_getgid
#  define SYS_getgroups __NR_getgroups
#  define SYS_getitimer __NR_getitimer
#  define SYS_getpeername __NR_getpeername
#  define SYS_getpgid __NR_getpgid
#  define SYS_getpgrp __NR_getpgrp
#  define SYS_getpid __NR_getpid
#  define SYS_getpmsg __NR_getpmsg
#  define SYS_getppid __NR_getppid
#  define SYS_getpriority __NR_getpriority
#  define SYS_getresgid __NR_getresgid
#  define SYS_getresuid __NR_getresuid
#  define SYS_getrlimit __NR_getrlimit
#  define SYS_getrusage __NR_getrusage
#  define SYS_getsid __NR_getsid
#  define SYS_getsockname __NR_getsockname
#  define SYS_getsockopt __NR_getsockopt
#  define SYS_gettid __NR_gettid
#  define SYS_gettimeofday __NR_gettimeofday
#  define SYS_getuid __NR_getuid
#  define SYS_getxattr __NR_getxattr
#  define SYS_init_module __NR_init_module
#  define SYS_io_cancel __NR_io_cancel
#  define SYS_io_destroy __NR_io_destroy
#  define SYS_io_getevents __NR_io_getevents
#  define SYS_io_setup __NR_io_setup
#  define SYS_io_submit __NR_io_submit
#  define SYS_ioctl __NR_ioctl
#  define SYS_keyctl __NR_keyctl
#  define SYS_kill __NR_kill
#  define SYS_lchown __NR_lchown
#  define SYS_lgetxattr __NR_lgetxattr
#  define SYS_link __NR_link
#  define SYS_listen __NR_listen
#  define SYS_listxattr __NR_listxattr
#  define SYS_llistxattr __NR_llistxattr
#  define SYS_lookup_dcookie __NR_lookup_dcookie
#  define SYS_lremovexattr __NR_lremovexattr
#  define SYS_lseek __NR_lseek
#  define SYS_lsetxattr __NR_lsetxattr
#  define SYS_lstat __NR_lstat
#  define SYS_madvise __NR_madvise
#  define SYS_mbind __NR_mbind
#  define SYS_mincore __NR_mincore
#  define SYS_mkdir __NR_mkdir
#  define SYS_mknod __NR_mknod
#  define SYS_mlock __NR_mlock
#  define SYS_mlockall __NR_mlockall
#  define SYS_mmap __NR_mmap
#  define SYS_mount __NR_mount
#  define SYS_mprotect __NR_mprotect
#  define SYS_mq_getsetattr __NR_mq_getsetattr
#  define SYS_mq_notify __NR_mq_notify
#  define SYS_mq_open __NR_mq_open
#  define SYS_mq_timedreceive __NR_mq_timedreceive
#  define SYS_mq_timedsend __NR_mq_timedsend
#  define SYS_mq_unlink __NR_mq_unlink
#  define SYS_mremap __NR_mremap
#  define SYS_msgctl __NR_msgctl
#  define SYS_msgget __NR_msgget
#  define SYS_msgrcv __NR_msgrcv
#  define SYS_msgsnd __NR_msgsnd
#  define SYS_msync __NR_msync
#  define SYS_munlock __NR_munlock
#  define SYS_munlockall __NR_munlockall
#  define SYS_munmap __NR_munmap
#  define SYS_nanosleep __NR_nanosleep
#  define SYS_nfsservctl __NR_nfsservctl
#  define SYS_open __NR_open
#  define SYS_pause __NR_pause
#  define SYS_personality __NR_personality
#  define SYS_pipe __NR_pipe
#  define SYS_pivot_root __NR_pivot_root
#  define SYS_poll __NR_poll
#  define SYS_prctl __NR_prctl
#  define SYS_pread64 __NR_pread64
#  define SYS_ptrace __NR_ptrace
#  define SYS_putpmsg __NR_putpmsg
#  define SYS_pwrite64 __NR_pwrite64
#  define SYS_query_module __NR_query_module
#  define SYS_quotactl __NR_quotactl
#  define SYS_read __NR_read
#  define SYS_readahead __NR_readahead
#  define SYS_readlink __NR_readlink
#  define SYS_readv __NR_readv
#  define SYS_reboot __NR_reboot
#  define SYS_recvfrom __NR_recvfrom
#  define SYS_recvmsg __NR_recvmsg
#  define SYS_remap_file_pages __NR_remap_file_pages
#  define SYS_removexattr __NR_removexattr
#  define SYS_rename __NR_rename
#  define SYS_request_key __NR_request_key
#  define SYS_reserved177 __NR_reserved177
#  define SYS_reserved193 __NR_reserved193
#  define SYS_restart_syscall __NR_restart_syscall
#  define SYS_rmdir __NR_rmdir
#  define SYS_rt_sigaction __NR_rt_sigaction
#  define SYS_rt_sigpending __NR_rt_sigpending
#  define SYS_rt_sigprocmask __NR_rt_sigprocmask
#  define SYS_rt_sigqueueinfo __NR_rt_sigqueueinfo
#  define SYS_rt_sigreturn __NR_rt_sigreturn
#  define SYS_rt_sigsuspend __NR_rt_sigsuspend
#  define SYS_rt_sigtimedwait __NR_rt_sigtimedwait
#  define SYS_sched_get_priority_max __NR_sched_get_priority_max
#  define SYS_sched_get_priority_min __NR_sched_get_priority_min
#  define SYS_sched_getaffinity __NR_sched_getaffinity
#  define SYS_sched_getparam __NR_sched_getparam
#  define SYS_sched_getscheduler __NR_sched_getscheduler
#  define SYS_sched_rr_get_interval __NR_sched_rr_get_interval
#  define SYS_sched_setaffinity __NR_sched_setaffinity
#  define SYS_sched_setparam __NR_sched_setparam
#  define SYS_sched_setscheduler __NR_sched_setscheduler
#  define SYS_sched_yield __NR_sched_yield
#  define SYS_semctl __NR_semctl
#  define SYS_semget __NR_semget
#  define SYS_semop __NR_semop
#  define SYS_semtimedop __NR_semtimedop
#  define SYS_sendfile __NR_sendfile
#  define SYS_sendfile64 __NR_sendfile64
#  define SYS_sendmsg __NR_sendmsg
#  define SYS_sendto __NR_sendto
#  define SYS_set_mempolicy __NR_set_mempolicy
#  define SYS_set_tid_address __NR_set_tid_address
#  define SYS_setdomainname __NR_setdomainname
#  define SYS_setfsgid __NR_setfsgid
#  define SYS_setfsuid __NR_setfsuid
#  define SYS_setgid __NR_setgid
#  define SYS_setgroups __NR_setgroups
#  define SYS_sethostname __NR_sethostname
#  define SYS_setitimer __NR_setitimer
#  define SYS_setpgid __NR_setpgid
#  define SYS_setpriority __NR_setpriority
#  define SYS_setregid __NR_setregid
#  define SYS_setresgid __NR_setresgid
#  define SYS_setresuid __NR_setresuid
#  define SYS_setreuid __NR_setreuid
#  define SYS_setrlimit __NR_setrlimit
#  define SYS_setsid __NR_setsid
#  define SYS_setsockopt __NR_setsockopt
#  define SYS_settimeofday __NR_settimeofday
#  define SYS_setuid __NR_setuid
#  define SYS_setxattr __NR_setxattr
#  define SYS_shmat __NR_shmat
#  define SYS_shmctl __NR_shmctl
#  define SYS_shmdt __NR_shmdt
#  define SYS_shmget __NR_shmget
#  define SYS_shutdown __NR_shutdown
#  define SYS_sigaltstack __NR_sigaltstack
#  define SYS_socket __NR_socket
#  define SYS_socketpair __NR_socketpair
#  define SYS_stat __NR_stat
#  define SYS_statfs __NR_statfs
#  define SYS_statfs64 __NR_statfs64
#  define SYS_swapoff __NR_swapoff
#  define SYS_swapon __NR_swapon
#  define SYS_symlink __NR_symlink
#  define SYS_sync __NR_sync
#  define SYS_sysfs __NR_sysfs
#  define SYS_sysinfo __NR_sysinfo
#  define SYS_syslog __NR_syslog
#  define SYS_sysmips __NR_sysmips
#  define SYS_tgkill __NR_tgkill
#  define SYS_timer_create __NR_timer_create
#  define SYS_timer_delete __NR_timer_delete
#  define SYS_timer_getoverrun __NR_timer_getoverrun
#  define SYS_timer_gettime __NR_timer_gettime
#  define SYS_timer_settime __NR_timer_settime
#  define SYS_times __NR_times
#  define SYS_tkill __NR_tkill
#  define SYS_truncate __NR_truncate
#  define SYS_umask __NR_umask
#  define SYS_umount2 __NR_umount2
#  define SYS_uname __NR_uname
#  define SYS_unlink __NR_unlink
#  define SYS_ustat __NR_ustat
#  define SYS_utime __NR_utime
#  define SYS_utimes __NR_utimes
#  define SYS_vhangup __NR_vhangup
#  define SYS_vserver __NR_vserver
#  define SYS_wait4 __NR_wait4
#  define SYS_waitid __NR_waitid
#  define SYS_write __NR_write
#  define SYS_writev __NR_writev
# endif
#elif _MIPS_SIM == _ABI64
# define SYS_Linux __NR_Linux
# define SYS_Linux_syscalls __NR_Linux_syscalls
# define SYS__newselect __NR__newselect
# define SYS__sysctl __NR__sysctl
# define SYS_accept __NR_accept
# define SYS_access __NR_access
# define SYS_acct __NR_acct
# define SYS_add_key __NR_add_key
# define SYS_adjtimex __NR_adjtimex
# define SYS_afs_syscall __NR_afs_syscall
# define SYS_alarm __NR_alarm
# define SYS_bind __NR_bind
# define SYS_brk __NR_brk
# define SYS_cachectl __NR_cachectl
# define SYS_cacheflush __NR_cacheflush
# define SYS_capget __NR_capget
# define SYS_capset __NR_capset
# define SYS_chdir __NR_chdir
# define SYS_chmod __NR_chmod
# define SYS_chown __NR_chown
# define SYS_chroot __NR_chroot
# define SYS_clock_getres __NR_clock_getres
# define SYS_clock_gettime __NR_clock_gettime
# define SYS_clock_nanosleep __NR_clock_nanosleep
# define SYS_clock_settime __NR_clock_settime
# define SYS_clone __NR_clone
# define SYS_close __NR_close
# define SYS_connect __NR_connect
# define SYS_creat __NR_creat
# define SYS_create_module __NR_create_module
# define SYS_delete_module __NR_delete_module
# define SYS_dup __NR_dup
# define SYS_dup2 __NR_dup2
# define SYS_epoll_create __NR_epoll_create
# define SYS_epoll_ctl __NR_epoll_ctl
# define SYS_epoll_wait __NR_epoll_wait
# define SYS_execve __NR_execve
# define SYS_exit __NR_exit
# define SYS_exit_group __NR_exit_group
# define SYS_fadvise64 __NR_fadvise64
# define SYS_fchdir __NR_fchdir
# define SYS_fchmod __NR_fchmod
# define SYS_fchown __NR_fchown
# define SYS_fcntl __NR_fcntl
# define SYS_fdatasync __NR_fdatasync
# define SYS_fgetxattr __NR_fgetxattr
# define SYS_flistxattr __NR_flistxattr
# define SYS_flock __NR_flock
# define SYS_fork __NR_fork
# define SYS_fremovexattr __NR_fremovexattr
# define SYS_fsetxattr __NR_fsetxattr
# define SYS_fstat __NR_fstat
# define SYS_fstatfs __NR_fstatfs
# define SYS_fsync __NR_fsync
# define SYS_ftruncate __NR_ftruncate
# define SYS_futex __NR_futex
# define SYS_get_kernel_syms __NR_get_kernel_syms
# define SYS_get_mempolicy __NR_get_mempolicy
# define SYS_getcwd __NR_getcwd
# define SYS_getdents __NR_getdents
# define SYS_getegid __NR_getegid
# define SYS_geteuid __NR_geteuid
# define SYS_getgid __NR_getgid
# define SYS_getgroups __NR_getgroups
# define SYS_getitimer __NR_getitimer
# define SYS_getpeername __NR_getpeername
# define SYS_getpgid __NR_getpgid
# define SYS_getpgrp __NR_getpgrp
# define SYS_getpid __NR_getpid
# define SYS_getpmsg __NR_getpmsg
# define SYS_getppid __NR_getppid
# define SYS_getpriority __NR_getpriority
# define SYS_getresgid __NR_getresgid
# define SYS_getresuid __NR_getresuid
# define SYS_getrlimit __NR_getrlimit
# define SYS_getrusage __NR_getrusage
# define SYS_getsid __NR_getsid
# define SYS_getsockname __NR_getsockname
# define SYS_getsockopt __NR_getsockopt
# define SYS_gettid __NR_gettid
# define SYS_gettimeofday __NR_gettimeofday
# define SYS_getuid __NR_getuid
# define SYS_getxattr __NR_getxattr
# define SYS_init_module __NR_init_module
# define SYS_io_cancel __NR_io_cancel
# define SYS_io_destroy __NR_io_destroy
# define SYS_io_getevents __NR_io_getevents
# define SYS_io_setup __NR_io_setup
# define SYS_io_submit __NR_io_submit
# define SYS_ioctl __NR_ioctl
# define SYS_keyctl __NR_keyctl
# define SYS_kill __NR_kill
# define SYS_lchown __NR_lchown
# define SYS_lgetxattr __NR_lgetxattr
# define SYS_link __NR_link
# define SYS_listen __NR_listen
# define SYS_listxattr __NR_listxattr
# define SYS_llistxattr __NR_llistxattr
# define SYS_lookup_dcookie __NR_lookup_dcookie
# define SYS_lremovexattr __NR_lremovexattr
# define SYS_lseek __NR_lseek
# define SYS_lsetxattr __NR_lsetxattr
# define SYS_lstat __NR_lstat
# define SYS_madvise __NR_madvise
# define SYS_mbind __NR_mbind
# define SYS_mincore __NR_mincore
# define SYS_mkdir __NR_mkdir
# define SYS_mknod __NR_mknod
# define SYS_mlock __NR_mlock
# define SYS_mlockall __NR_mlockall
# define SYS_mmap __NR_mmap
# define SYS_mount __NR_mount
# define SYS_mprotect __NR_mprotect
# define SYS_mq_getsetattr __NR_mq_getsetattr
# define SYS_mq_notify __NR_mq_notify
# define SYS_mq_open __NR_mq_open
# define SYS_mq_timedreceive __NR_mq_timedreceive
# define SYS_mq_timedsend __NR_mq_timedsend
# define SYS_mq_unlink __NR_mq_unlink
# define SYS_mremap __NR_mremap
# define SYS_msgctl __NR_msgctl
# define SYS_msgget __NR_msgget
# define SYS_msgrcv __NR_msgrcv
# define SYS_msgsnd __NR_msgsnd
# define SYS_msync __NR_msync
# define SYS_munlock __NR_munlock
# define SYS_munlockall __NR_munlockall
# define SYS_munmap __NR_munmap
# define SYS_nanosleep __NR_nanosleep
# define SYS_nfsservctl __NR_nfsservctl
# define SYS_open __NR_open
# define SYS_pause __NR_pause
# define SYS_personality __NR_personality
# define SYS_pipe __NR_pipe
# define SYS_pivot_root __NR_pivot_root
# define SYS_poll __NR_poll
# define SYS_prctl __NR_prctl
# define SYS_pread64 __NR_pread64
# define SYS_ptrace __NR_ptrace
# define SYS_putpmsg __NR_putpmsg
# define SYS_pwrite64 __NR_pwrite64
# define SYS_query_module __NR_query_module
# define SYS_quotactl __NR_quotactl
# define SYS_read __NR_read
# define SYS_readahead __NR_readahead
# define SYS_readlink __NR_readlink
# define SYS_readv __NR_readv
# define SYS_reboot __NR_reboot
# define SYS_recvfrom __NR_recvfrom
# define SYS_recvmsg __NR_recvmsg
# define SYS_remap_file_pages __NR_remap_file_pages
# define SYS_removexattr __NR_removexattr
# define SYS_rename __NR_rename
# define SYS_request_key __NR_request_key
# define SYS_reserved177 __NR_reserved177
# define SYS_reserved193 __NR_reserved193
# define SYS_restart_syscall __NR_restart_syscall
# define SYS_rmdir __NR_rmdir
# define SYS_rt_sigaction __NR_rt_sigaction
# define SYS_rt_sigpending __NR_rt_sigpending
# define SYS_rt_sigprocmask __NR_rt_sigprocmask
# define SYS_rt_sigqueueinfo __NR_rt_sigqueueinfo
# define SYS_rt_sigreturn __NR_rt_sigreturn
# define SYS_rt_sigsuspend __NR_rt_sigsuspend
# define SYS_rt_sigtimedwait __NR_rt_sigtimedwait
# define SYS_sched_get_priority_max __NR_sched_get_priority_max
# define SYS_sched_get_priority_min __NR_sched_get_priority_min
# define SYS_sched_getaffinity __NR_sched_getaffinity
# define SYS_sched_getparam __NR_sched_getparam
# define SYS_sched_getscheduler __NR_sched_getscheduler
# define SYS_sched_rr_get_interval __NR_sched_rr_get_interval
# define SYS_sched_setaffinity __NR_sched_setaffinity
# define SYS_sched_setparam __NR_sched_setparam
# define SYS_sched_setscheduler __NR_sched_setscheduler
# define SYS_sched_yield __NR_sched_yield
# define SYS_semctl __NR_semctl
# define SYS_semget __NR_semget
# define SYS_semop __NR_semop
# define SYS_semtimedop __NR_semtimedop
# define SYS_sendfile __NR_sendfile
# define SYS_sendmsg __NR_sendmsg
# define SYS_sendto __NR_sendto
# define SYS_set_mempolicy __NR_set_mempolicy
# define SYS_set_tid_address __NR_set_tid_address
# define SYS_setdomainname __NR_setdomainname
# define SYS_setfsgid __NR_setfsgid
# define SYS_setfsuid __NR_setfsuid
# define SYS_setgid __NR_setgid
# define SYS_setgroups __NR_setgroups
# define SYS_sethostname __NR_sethostname
# define SYS_setitimer __NR_setitimer
# define SYS_setpgid __NR_setpgid
# define SYS_setpriority __NR_setpriority
# define SYS_setregid __NR_setregid
# define SYS_setresgid __NR_setresgid
# define SYS_setresuid __NR_setresuid
# define SYS_setreuid __NR_setreuid
# define SYS_setrlimit __NR_setrlimit
# define SYS_setsid __NR_setsid
# define SYS_setsockopt __NR_setsockopt
# define SYS_settimeofday __NR_settimeofday
# define SYS_setuid __NR_setuid
# define SYS_setxattr __NR_setxattr
# define SYS_shmat __NR_shmat
# define SYS_shmctl __NR_shmctl
# define SYS_shmdt __NR_shmdt
# define SYS_shmget __NR_shmget
# define SYS_shutdown __NR_shutdown
# define SYS_sigaltstack __NR_sigaltstack
# define SYS_socket __NR_socket
# define SYS_socketpair __NR_socketpair
# define SYS_stat __NR_stat
# define SYS_statfs __NR_statfs
# define SYS_swapoff __NR_swapoff
# define SYS_swapon __NR_swapon
# define SYS_symlink __NR_symlink
# define SYS_sync __NR_sync
# define SYS_sysfs __NR_sysfs
# define SYS_sysinfo __NR_sysinfo
# define SYS_syslog __NR_syslog
# define SYS_sysmips __NR_sysmips
# define SYS_tgkill __NR_tgkill
# define SYS_timer_create __NR_timer_create
# define SYS_timer_delete __NR_timer_delete
# define SYS_timer_getoverrun __NR_timer_getoverrun
# define SYS_timer_gettime __NR_timer_gettime
# define SYS_timer_settime __NR_timer_settime
# define SYS_times __NR_times
# define SYS_tkill __NR_tkill
# define SYS_truncate __NR_truncate
# define SYS_umask __NR_umask
# define SYS_umount2 __NR_umount2
# define SYS_uname __NR_uname
# define SYS_unlink __NR_unlink
# define SYS_ustat __NR_ustat
# define SYS_utime __NR_utime
# define SYS_utimes __NR_utimes
# define SYS_vhangup __NR_vhangup
# define SYS_vserver __NR_vserver
# define SYS_wait4 __NR_wait4
# define SYS_waitid __NR_waitid
# define SYS_write __NR_write
# define SYS_writev __NR_writev
#else
# ifdef __NR_O32_open
#  define SYS_Linux __NR_O32_Linux
#  define SYS_Linux_syscalls __NR_O32_Linux_syscalls
#  define SYS__llseek __NR_O32__llseek
#  define SYS__newselect __NR_O32__newselect
#  define SYS__sysctl __NR_O32__sysctl
#  define SYS_accept __NR_O32_accept
#  define SYS_access __NR_O32_access
#  define SYS_acct __NR_O32_acct
#  define SYS_add_key __NR_O32_add_key
#  define SYS_adjtimex __NR_O32_adjtimex
#  define SYS_afs_syscall __NR_O32_afs_syscall
#  define SYS_alarm __NR_O32_alarm
#  define SYS_bdflush __NR_O32_bdflush
#  define SYS_bind __NR_O32_bind
#  define SYS_break __NR_O32_break
#  define SYS_brk __NR_O32_brk
#  define SYS_cachectl __NR_O32_cachectl
#  define SYS_cacheflush __NR_O32_cacheflush
#  define SYS_capget __NR_O32_capget
#  define SYS_capset __NR_O32_capset
#  define SYS_chdir __NR_O32_chdir
#  define SYS_chmod __NR_O32_chmod
#  define SYS_chown __NR_O32_chown
#  define SYS_chroot __NR_O32_chroot
#  define SYS_clock_getres __NR_O32_clock_getres
#  define SYS_clock_gettime __NR_O32_clock_gettime
#  define SYS_clock_nanosleep __NR_O32_clock_nanosleep
#  define SYS_clock_settime __NR_O32_clock_settime
#  define SYS_clone __NR_O32_clone
#  define SYS_close __NR_O32_close
#  define SYS_connect __NR_O32_connect
#  define SYS_creat __NR_O32_creat
#  define SYS_create_module __NR_O32_create_module
#  define SYS_delete_module __NR_O32_delete_module
#  define SYS_dup __NR_O32_dup
#  define SYS_dup2 __NR_O32_dup2
#  define SYS_epoll_create __NR_O32_epoll_create
#  define SYS_epoll_ctl __NR_O32_epoll_ctl
#  define SYS_epoll_wait __NR_O32_epoll_wait
#  define SYS_execve __NR_O32_execve
#  define SYS_exit __NR_O32_exit
#  define SYS_exit_group __NR_O32_exit_group
#  define SYS_fadvise64 __NR_O32_fadvise64
#  define SYS_fchdir __NR_O32_fchdir
#  define SYS_fchmod __NR_O32_fchmod
#  define SYS_fchown __NR_O32_fchown
#  define SYS_fcntl __NR_O32_fcntl
#  define SYS_fcntl64 __NR_O32_fcntl64
#  define SYS_fdatasync __NR_O32_fdatasync
#  define SYS_fgetxattr __NR_O32_fgetxattr
#  define SYS_flistxattr __NR_O32_flistxattr
#  define SYS_flock __NR_O32_flock
#  define SYS_fork __NR_O32_fork
#  define SYS_fremovexattr __NR_O32_fremovexattr
#  define SYS_fsetxattr __NR_O32_fsetxattr
#  define SYS_fstat __NR_O32_fstat
#  define SYS_fstat64 __NR_O32_fstat64
#  define SYS_fstatfs __NR_O32_fstatfs
#  define SYS_fstatfs64 __NR_O32_fstatfs64
#  define SYS_fsync __NR_O32_fsync
#  define SYS_ftime __NR_O32_ftime
#  define SYS_ftruncate __NR_O32_ftruncate
#  define SYS_ftruncate64 __NR_O32_ftruncate64
#  define SYS_futex __NR_O32_futex
#  define SYS_get_kernel_syms __NR_O32_get_kernel_syms
#  define SYS_get_mempolicy __NR_O32_get_mempolicy
#  define SYS_getcwd __NR_O32_getcwd
#  define SYS_getdents __NR_O32_getdents
#  define SYS_getdents64 __NR_O32_getdents64
#  define SYS_getegid __NR_O32_getegid
#  define SYS_geteuid __NR_O32_geteuid
#  define SYS_getgid __NR_O32_getgid
#  define SYS_getgroups __NR_O32_getgroups
#  define SYS_getitimer __NR_O32_getitimer
#  define SYS_getpeername __NR_O32_getpeername
#  define SYS_getpgid __NR_O32_getpgid
#  define SYS_getpgrp __NR_O32_getpgrp
#  define SYS_getpid __NR_O32_getpid
#  define SYS_getpmsg __NR_O32_getpmsg
#  define SYS_getppid __NR_O32_getppid
#  define SYS_getpriority __NR_O32_getpriority
#  define SYS_getresgid __NR_O32_getresgid
#  define SYS_getresuid __NR_O32_getresuid
#  define SYS_getrlimit __NR_O32_getrlimit
#  define SYS_getrusage __NR_O32_getrusage
#  define SYS_getsid __NR_O32_getsid
#  define SYS_getsockname __NR_O32_getsockname
#  define SYS_getsockopt __NR_O32_getsockopt
#  define SYS_gettid __NR_O32_gettid
#  define SYS_gettimeofday __NR_O32_gettimeofday
#  define SYS_getuid __NR_O32_getuid
#  define SYS_getxattr __NR_O32_getxattr
#  define SYS_gtty __NR_O32_gtty
#  define SYS_idle __NR_O32_idle
#  define SYS_init_module __NR_O32_init_module
#  define SYS_io_cancel __NR_O32_io_cancel
#  define SYS_io_destroy __NR_O32_io_destroy
#  define SYS_io_getevents __NR_O32_io_getevents
#  define SYS_io_setup __NR_O32_io_setup
#  define SYS_io_submit __NR_O32_io_submit
#  define SYS_ioctl __NR_O32_ioctl
#  define SYS_ioperm __NR_O32_ioperm
#  define SYS_iopl __NR_O32_iopl
#  define SYS_ipc __NR_O32_ipc
#  define SYS_keyctl __NR_O32_keyctl
#  define SYS_kill __NR_O32_kill
#  define SYS_lchown __NR_O32_lchown
#  define SYS_lgetxattr __NR_O32_lgetxattr
#  define SYS_link __NR_O32_link
#  define SYS_listen __NR_O32_listen
#  define SYS_listxattr __NR_O32_listxattr
#  define SYS_llistxattr __NR_O32_llistxattr
#  define SYS_lock __NR_O32_lock
#  define SYS_lookup_dcookie __NR_O32_lookup_dcookie
#  define SYS_lremovexattr __NR_O32_lremovexattr
#  define SYS_lseek __NR_O32_lseek
#  define SYS_lsetxattr __NR_O32_lsetxattr
#  define SYS_lstat __NR_O32_lstat
#  define SYS_lstat64 __NR_O32_lstat64
#  define SYS_madvise __NR_O32_madvise
#  define SYS_mbind __NR_O32_mbind
#  define SYS_mincore __NR_O32_mincore
#  define SYS_mkdir __NR_O32_mkdir
#  define SYS_mknod __NR_O32_mknod
#  define SYS_mlock __NR_O32_mlock
#  define SYS_mlockall __NR_O32_mlockall
#  define SYS_mmap __NR_O32_mmap
#  define SYS_mmap2 __NR_O32_mmap2
#  define SYS_modify_ldt __NR_O32_modify_ldt
#  define SYS_mount __NR_O32_mount
#  define SYS_mprotect __NR_O32_mprotect
#  define SYS_mpx __NR_O32_mpx
#  define SYS_mq_getsetattr __NR_O32_mq_getsetattr
#  define SYS_mq_notify __NR_O32_mq_notify
#  define SYS_mq_open __NR_O32_mq_open
#  define SYS_mq_timedreceive __NR_O32_mq_timedreceive
#  define SYS_mq_timedsend __NR_O32_mq_timedsend
#  define SYS_mq_unlink __NR_O32_mq_unlink
#  define SYS_mremap __NR_O32_mremap
#  define SYS_msync __NR_O32_msync
#  define SYS_munlock __NR_O32_munlock
#  define SYS_munlockall __NR_O32_munlockall
#  define SYS_munmap __NR_O32_munmap
#  define SYS_nanosleep __NR_O32_nanosleep
#  define SYS_nfsservctl __NR_O32_nfsservctl
#  define SYS_nice __NR_O32_nice
#  define SYS_open __NR_O32_open
#  define SYS_pause __NR_O32_pause
#  define SYS_personality __NR_O32_personality
#  define SYS_pipe __NR_O32_pipe
#  define SYS_pivot_root __NR_O32_pivot_root
#  define SYS_poll __NR_O32_poll
#  define SYS_prctl __NR_O32_prctl
#  define SYS_pread64 __NR_O32_pread64
#  define SYS_prof __NR_O32_prof
#  define SYS_profil __NR_O32_profil
#  define SYS_ptrace __NR_O32_ptrace
#  define SYS_putpmsg __NR_O32_putpmsg
#  define SYS_pwrite64 __NR_O32_pwrite64
#  define SYS_query_module __NR_O32_query_module
#  define SYS_quotactl __NR_O32_quotactl
#  define SYS_read __NR_O32_read
#  define SYS_readahead __NR_O32_readahead
#  define SYS_readdir __NR_O32_readdir
#  define SYS_readlink __NR_O32_readlink
#  define SYS_readv __NR_O32_readv
#  define SYS_reboot __NR_O32_reboot
#  define SYS_recv __NR_O32_recv
#  define SYS_recvfrom __NR_O32_recvfrom
#  define SYS_recvmsg __NR_O32_recvmsg
#  define SYS_remap_file_pages __NR_O32_remap_file_pages
#  define SYS_removexattr __NR_O32_removexattr
#  define SYS_rename __NR_O32_rename
#  define SYS_request_key __NR_O32_request_key
#  define SYS_reserved221 __NR_O32_reserved221
#  define SYS_reserved82 __NR_O32_reserved82
#  define SYS_restart_syscall __NR_O32_restart_syscall
#  define SYS_rmdir __NR_O32_rmdir
#  define SYS_rt_sigaction __NR_O32_rt_sigaction
#  define SYS_rt_sigpending __NR_O32_rt_sigpending
#  define SYS_rt_sigprocmask __NR_O32_rt_sigprocmask
#  define SYS_rt_sigqueueinfo __NR_O32_rt_sigqueueinfo
#  define SYS_rt_sigreturn __NR_O32_rt_sigreturn
#  define SYS_rt_sigsuspend __NR_O32_rt_sigsuspend
#  define SYS_rt_sigtimedwait __NR_O32_rt_sigtimedwait
#  define SYS_sched_get_priority_max __NR_O32_sched_get_priority_max
#  define SYS_sched_get_priority_min __NR_O32_sched_get_priority_min
#  define SYS_sched_getaffinity __NR_O32_sched_getaffinity
#  define SYS_sched_getparam __NR_O32_sched_getparam
#  define SYS_sched_getscheduler __NR_O32_sched_getscheduler
#  define SYS_sched_rr_get_interval __NR_O32_sched_rr_get_interval
#  define SYS_sched_setaffinity __NR_O32_sched_setaffinity
#  define SYS_sched_setparam __NR_O32_sched_setparam
#  define SYS_sched_setscheduler __NR_O32_sched_setscheduler
#  define SYS_sched_yield __NR_O32_sched_yield
#  define SYS_send __NR_O32_send
#  define SYS_sendfile __NR_O32_sendfile
#  define SYS_sendfile64 __NR_O32_sendfile64
#  define SYS_sendmsg __NR_O32_sendmsg
#  define SYS_sendto __NR_O32_sendto
#  define SYS_set_mempolicy __NR_O32_set_mempolicy
#  define SYS_set_tid_address __NR_O32_set_tid_address
#  define SYS_setdomainname __NR_O32_setdomainname
#  define SYS_setfsgid __NR_O32_setfsgid
#  define SYS_setfsuid __NR_O32_setfsuid
#  define SYS_setgid __NR_O32_setgid
#  define SYS_setgroups __NR_O32_setgroups
#  define SYS_sethostname __NR_O32_sethostname
#  define SYS_setitimer __NR_O32_setitimer
#  define SYS_setpgid __NR_O32_setpgid
#  define SYS_setpriority __NR_O32_setpriority
#  define SYS_setregid __NR_O32_setregid
#  define SYS_setresgid __NR_O32_setresgid
#  define SYS_setresuid __NR_O32_setresuid
#  define SYS_setreuid __NR_O32_setreuid
#  define SYS_setrlimit __NR_O32_setrlimit
#  define SYS_setsid __NR_O32_setsid
#  define SYS_setsockopt __NR_O32_setsockopt
#  define SYS_settimeofday __NR_O32_settimeofday
#  define SYS_setuid __NR_O32_setuid
#  define SYS_setxattr __NR_O32_setxattr
#  define SYS_sgetmask __NR_O32_sgetmask
#  define SYS_shutdown __NR_O32_shutdown
#  define SYS_sigaction __NR_O32_sigaction
#  define SYS_sigaltstack __NR_O32_sigaltstack
#  define SYS_signal __NR_O32_signal
#  define SYS_sigpending __NR_O32_sigpending
#  define SYS_sigprocmask __NR_O32_sigprocmask
#  define SYS_sigreturn __NR_O32_sigreturn
#  define SYS_sigsuspend __NR_O32_sigsuspend
#  define SYS_socket __NR_O32_socket
#  define SYS_socketcall __NR_O32_socketcall
#  define SYS_socketpair __NR_O32_socketpair
#  define SYS_ssetmask __NR_O32_ssetmask
#  define SYS_stat __NR_O32_stat
#  define SYS_stat64 __NR_O32_stat64
#  define SYS_statfs __NR_O32_statfs
#  define SYS_statfs64 __NR_O32_statfs64
#  define SYS_stime __NR_O32_stime
#  define SYS_stty __NR_O32_stty
#  define SYS_swapoff __NR_O32_swapoff
#  define SYS_swapon __NR_O32_swapon
#  define SYS_symlink __NR_O32_symlink
#  define SYS_sync __NR_O32_sync
#  define SYS_syscall __NR_O32_syscall
#  define SYS_sysfs __NR_O32_sysfs
#  define SYS_sysinfo __NR_O32_sysinfo
#  define SYS_syslog __NR_O32_syslog
#  define SYS_sysmips __NR_O32_sysmips
#  define SYS_tgkill __NR_O32_tgkill
#  define SYS_time __NR_O32_time
#  define SYS_timer_create __NR_O32_timer_create
#  define SYS_timer_delete __NR_O32_timer_delete
#  define SYS_timer_getoverrun __NR_O32_timer_getoverrun
#  define SYS_timer_gettime __NR_O32_timer_gettime
#  define SYS_timer_settime __NR_O32_timer_settime
#  define SYS_times __NR_O32_times
#  define SYS_tkill __NR_O32_tkill
#  define SYS_truncate __NR_O32_truncate
#  define SYS_truncate64 __NR_O32_truncate64
#  define SYS_ulimit __NR_O32_ulimit
#  define SYS_umask __NR_O32_umask
#  define SYS_umount __NR_O32_umount
#  define SYS_umount2 __NR_O32_umount2
#  define SYS_uname __NR_O32_uname
#  define SYS_unlink __NR_O32_unlink
#  define SYS_unused109 __NR_O32_unused109
#  define SYS_unused150 __NR_O32_unused150
#  define SYS_unused18 __NR_O32_unused18
#  define SYS_unused28 __NR_O32_unused28
#  define SYS_unused59 __NR_O32_unused59
#  define SYS_unused84 __NR_O32_unused84
#  define SYS_uselib __NR_O32_uselib
#  define SYS_ustat __NR_O32_ustat
#  define SYS_utime __NR_O32_utime
#  define SYS_utimes __NR_O32_utimes
#  define SYS_vhangup __NR_O32_vhangup
#  define SYS_vm86 __NR_O32_vm86
#  define SYS_vserver __NR_O32_vserver
#  define SYS_wait4 __NR_O32_wait4
#  define SYS_waitid __NR_O32_waitid
#  define SYS_waitpid __NR_O32_waitpid
#  define SYS_write __NR_O32_write
#  define SYS_writev __NR_O32_writev
# else
#  define SYS_Linux __NR_Linux
#  define SYS_Linux_syscalls __NR_Linux_syscalls
#  define SYS__llseek __NR__llseek
#  define SYS__newselect __NR__newselect
#  define SYS__sysctl __NR__sysctl
#  define SYS_accept __NR_accept
#  define SYS_access __NR_access
#  define SYS_acct __NR_acct
#  define SYS_add_key __NR_add_key
#  define SYS_adjtimex __NR_adjtimex
#  define SYS_afs_syscall __NR_afs_syscall
#  define SYS_alarm __NR_alarm
#  define SYS_bdflush __NR_bdflush
#  define SYS_bind __NR_bind
#  define SYS_break __NR_break
#  define SYS_brk __NR_brk
#  define SYS_cachectl __NR_cachectl
#  define SYS_cacheflush __NR_cacheflush
#  define SYS_capget __NR_capget
#  define SYS_capset __NR_capset
#  define SYS_chdir __NR_chdir
#  define SYS_chmod __NR_chmod
#  define SYS_chown __NR_chown
#  define SYS_chroot __NR_chroot
#  define SYS_clock_getres __NR_clock_getres
#  define SYS_clock_gettime __NR_clock_gettime
#  define SYS_clock_nanosleep __NR_clock_nanosleep
#  define SYS_clock_settime __NR_clock_settime
#  define SYS_clone __NR_clone
#  define SYS_close __NR_close
#  define SYS_connect __NR_connect
#  define SYS_creat __NR_creat
#  define SYS_create_module __NR_create_module
#  define SYS_delete_module __NR_delete_module
#  define SYS_dup __NR_dup
#  define SYS_dup2 __NR_dup2
#  define SYS_epoll_create __NR_epoll_create
#  define SYS_epoll_ctl __NR_epoll_ctl
#  define SYS_epoll_wait __NR_epoll_wait
#  define SYS_execve __NR_execve
#  define SYS_exit __NR_exit
#  define SYS_exit_group __NR_exit_group
#  define SYS_fadvise64 __NR_fadvise64
#  define SYS_fchdir __NR_fchdir
#  define SYS_fchmod __NR_fchmod
#  define SYS_fchown __NR_fchown
#  define SYS_fcntl __NR_fcntl
#  define SYS_fcntl64 __NR_fcntl64
#  define SYS_fdatasync __NR_fdatasync
#  define SYS_fgetxattr __NR_fgetxattr
#  define SYS_flistxattr __NR_flistxattr
#  define SYS_flock __NR_flock
#  define SYS_fork __NR_fork
#  define SYS_fremovexattr __NR_fremovexattr
#  define SYS_fsetxattr __NR_fsetxattr
#  define SYS_fstat __NR_fstat
#  define SYS_fstat64 __NR_fstat64
#  define SYS_fstatfs __NR_fstatfs
#  define SYS_fstatfs64 __NR_fstatfs64
#  define SYS_fsync __NR_fsync
#  define SYS_ftime __NR_ftime
#  define SYS_ftruncate __NR_ftruncate
#  define SYS_ftruncate64 __NR_ftruncate64
#  define SYS_futex __NR_futex
#  define SYS_get_kernel_syms __NR_get_kernel_syms
#  define SYS_get_mempolicy __NR_get_mempolicy
#  define SYS_getcwd __NR_getcwd
#  define SYS_getdents __NR_getdents
#  define SYS_getdents64 __NR_getdents64
#  define SYS_getegid __NR_getegid
#  define SYS_geteuid __NR_geteuid
#  define SYS_getgid __NR_getgid
#  define SYS_getgroups __NR_getgroups
#  define SYS_getitimer __NR_getitimer
#  define SYS_getpeername __NR_getpeername
#  define SYS_getpgid __NR_getpgid
#  define SYS_getpgrp __NR_getpgrp
#  define SYS_getpid __NR_getpid
#  define SYS_getpmsg __NR_getpmsg
#  define SYS_getppid __NR_getppid
#  define SYS_getpriority __NR_getpriority
#  define SYS_getresgid __NR_getresgid
#  define SYS_getresuid __NR_getresuid
#  define SYS_getrlimit __NR_getrlimit
#  define SYS_getrusage __NR_getrusage
#  define SYS_getsid __NR_getsid
#  define SYS_getsockname __NR_getsockname
#  define SYS_getsockopt __NR_getsockopt
#  define SYS_gettid __NR_gettid
#  define SYS_gettimeofday __NR_gettimeofday
#  define SYS_getuid __NR_getuid
#  define SYS_getxattr __NR_getxattr
#  define SYS_gtty __NR_gtty
#  define SYS_idle __NR_idle
#  define SYS_init_module __NR_init_module
#  define SYS_io_cancel __NR_io_cancel
#  define SYS_io_destroy __NR_io_destroy
#  define SYS_io_getevents __NR_io_getevents
#  define SYS_io_setup __NR_io_setup
#  define SYS_io_submit __NR_io_submit
#  define SYS_ioctl __NR_ioctl
#  define SYS_ioperm __NR_ioperm
#  define SYS_iopl __NR_iopl
#  define SYS_ipc __NR_ipc
#  define SYS_keyctl __NR_keyctl
#  define SYS_kill __NR_kill
#  define SYS_lchown __NR_lchown
#  define SYS_lgetxattr __NR_lgetxattr
#  define SYS_link __NR_link
#  define SYS_listen __NR_listen
#  define SYS_listxattr __NR_listxattr
#  define SYS_llistxattr __NR_llistxattr
#  define SYS_lock __NR_lock
#  define SYS_lookup_dcookie __NR_lookup_dcookie
#  define SYS_lremovexattr __NR_lremovexattr
#  define SYS_lseek __NR_lseek
#  define SYS_lsetxattr __NR_lsetxattr
#  define SYS_lstat __NR_lstat
#  define SYS_lstat64 __NR_lstat64
#  define SYS_madvise __NR_madvise
#  define SYS_mbind __NR_mbind
#  define SYS_mincore __NR_mincore
#  define SYS_mkdir __NR_mkdir
#  define SYS_mknod __NR_mknod
#  define SYS_mlock __NR_mlock
#  define SYS_mlockall __NR_mlockall
#  define SYS_mmap __NR_mmap
#  define SYS_mmap2 __NR_mmap2
#  define SYS_modify_ldt __NR_modify_ldt
#  define SYS_mount __NR_mount
#  define SYS_mprotect __NR_mprotect
#  define SYS_mpx __NR_mpx
#  define SYS_mq_getsetattr __NR_mq_getsetattr
#  define SYS_mq_notify __NR_mq_notify
#  define SYS_mq_open __NR_mq_open
#  define SYS_mq_timedreceive __NR_mq_timedreceive
#  define SYS_mq_timedsend __NR_mq_timedsend
#  define SYS_mq_unlink __NR_mq_unlink
#  define SYS_mremap __NR_mremap
#  define SYS_msync __NR_msync
#  define SYS_munlock __NR_munlock
#  define SYS_munlockall __NR_munlockall
#  define SYS_munmap __NR_munmap
#  define SYS_nanosleep __NR_nanosleep
#  define SYS_nfsservctl __NR_nfsservctl
#  define SYS_nice __NR_nice
#  define SYS_open __NR_open
#  define SYS_pause __NR_pause
#  define SYS_personality __NR_personality
#  define SYS_pipe __NR_pipe
#  define SYS_pivot_root __NR_pivot_root
#  define SYS_poll __NR_poll
#  define SYS_prctl __NR_prctl
#  define SYS_pread64 __NR_pread64
#  define SYS_prof __NR_prof
#  define SYS_profil __NR_profil
#  define SYS_ptrace __NR_ptrace
#  define SYS_putpmsg __NR_putpmsg
#  define SYS_pwrite64 __NR_pwrite64
#  define SYS_query_module __NR_query_module
#  define SYS_quotactl __NR_quotactl
#  define SYS_read __NR_read
#  define SYS_readahead __NR_readahead
#  define SYS_readdir __NR_readdir
#  define SYS_readlink __NR_readlink
#  define SYS_readv __NR_readv
#  define SYS_reboot __NR_reboot
#  define SYS_recv __NR_recv
#  define SYS_recvfrom __NR_recvfrom
#  define SYS_recvmsg __NR_recvmsg
#  define SYS_remap_file_pages __NR_remap_file_pages
#  define SYS_removexattr __NR_removexattr
#  define SYS_rename __NR_rename
#  define SYS_request_key __NR_request_key
#  define SYS_reserved221 __NR_reserved221
#  define SYS_reserved82 __NR_reserved82
#  define SYS_restart_syscall __NR_restart_syscall
#  define SYS_rmdir __NR_rmdir
#  define SYS_rt_sigaction __NR_rt_sigaction
#  define SYS_rt_sigpending __NR_rt_sigpending
#  define SYS_rt_sigprocmask __NR_rt_sigprocmask
#  define SYS_rt_sigqueueinfo __NR_rt_sigqueueinfo
#  define SYS_rt_sigreturn __NR_rt_sigreturn
#  define SYS_rt_sigsuspend __NR_rt_sigsuspend
#  define SYS_rt_sigtimedwait __NR_rt_sigtimedwait
#  define SYS_sched_get_priority_max __NR_sched_get_priority_max
#  define SYS_sched_get_priority_min __NR_sched_get_priority_min
#  define SYS_sched_getaffinity __NR_sched_getaffinity
#  define SYS_sched_getparam __NR_sched_getparam
#  define SYS_sched_getscheduler __NR_sched_getscheduler
#  define SYS_sched_rr_get_interval __NR_sched_rr_get_interval
#  define SYS_sched_setaffinity __NR_sched_setaffinity
#  define SYS_sched_setparam __NR_sched_setparam
#  define SYS_sched_setscheduler __NR_sched_setscheduler
#  define SYS_sched_yield __NR_sched_yield
#  define SYS_send __NR_send
#  define SYS_sendfile __NR_sendfile
#  define SYS_sendfile64 __NR_sendfile64
#  define SYS_sendmsg __NR_sendmsg
#  define SYS_sendto __NR_sendto
#  define SYS_set_mempolicy __NR_set_mempolicy
#  define SYS_set_tid_address __NR_set_tid_address
#  define SYS_setdomainname __NR_setdomainname
#  define SYS_setfsgid __NR_setfsgid
#  define SYS_setfsuid __NR_setfsuid
#  define SYS_setgid __NR_setgid
#  define SYS_setgroups __NR_setgroups
#  define SYS_sethostname __NR_sethostname
#  define SYS_setitimer __NR_setitimer
#  define SYS_setpgid __NR_setpgid
#  define SYS_setpriority __NR_setpriority
#  define SYS_setregid __NR_setregid
#  define SYS_setresgid __NR_setresgid
#  define SYS_setresuid __NR_setresuid
#  define SYS_setreuid __NR_setreuid
#  define SYS_setrlimit __NR_setrlimit
#  define SYS_setsid __NR_setsid
#  define SYS_setsockopt __NR_setsockopt
#  define SYS_settimeofday __NR_settimeofday
#  define SYS_setuid __NR_setuid
#  define SYS_setxattr __NR_setxattr
#  define SYS_sgetmask __NR_sgetmask
#  define SYS_shutdown __NR_shutdown
#  define SYS_sigaction __NR_sigaction
#  define SYS_sigaltstack __NR_sigaltstack
#  define SYS_signal __NR_signal
#  define SYS_sigpending __NR_sigpending
#  define SYS_sigprocmask __NR_sigprocmask
#  define SYS_sigreturn __NR_sigreturn
#  define SYS_sigsuspend __NR_sigsuspend
#  define SYS_socket __NR_socket
#  define SYS_socketcall __NR_socketcall
#  define SYS_socketpair __NR_socketpair
#  define SYS_ssetmask __NR_ssetmask
#  define SYS_stat __NR_stat
#  define SYS_stat64 __NR_stat64
#  define SYS_statfs __NR_statfs
#  define SYS_statfs64 __NR_statfs64
#  define SYS_stime __NR_stime
#  define SYS_stty __NR_stty
#  define SYS_swapoff __NR_swapoff
#  define SYS_swapon __NR_swapon
#  define SYS_symlink __NR_symlink
#  define SYS_sync __NR_sync
#  define SYS_syscall __NR_syscall
#  define SYS_sysfs __NR_sysfs
#  define SYS_sysinfo __NR_sysinfo
#  define SYS_syslog __NR_syslog
#  define SYS_sysmips __NR_sysmips
#  define SYS_tgkill __NR_tgkill
#  define SYS_time __NR_time
#  define SYS_timer_create __NR_timer_create
#  define SYS_timer_delete __NR_timer_delete
#  define SYS_timer_getoverrun __NR_timer_getoverrun
#  define SYS_timer_gettime __NR_timer_gettime
#  define SYS_timer_settime __NR_timer_settime
#  define SYS_times __NR_times
#  define SYS_tkill __NR_tkill
#  define SYS_truncate __NR_truncate
#  define SYS_truncate64 __NR_truncate64
#  define SYS_ulimit __NR_ulimit
#  define SYS_umask __NR_umask
#  define SYS_umount __NR_umount
#  define SYS_umount2 __NR_umount2
#  define SYS_uname __NR_uname
#  define SYS_unlink __NR_unlink
#  define SYS_unused109 __NR_unused109
#  define SYS_unused150 __NR_unused150
#  define SYS_unused18 __NR_unused18
#  define SYS_unused28 __NR_unused28
#  define SYS_unused59 __NR_unused59
#  define SYS_unused84 __NR_unused84
#  define SYS_uselib __NR_uselib
#  define SYS_ustat __NR_ustat
#  define SYS_utime __NR_utime
#  define SYS_utimes __NR_utimes
#  define SYS_vhangup __NR_vhangup
#  define SYS_vm86 __NR_vm86
#  define SYS_vserver __NR_vserver
#  define SYS_wait4 __NR_wait4
#  define SYS_waitid __NR_waitid
#  define SYS_waitpid __NR_waitpid
#  define SYS_write __NR_write
#  define SYS_writev __NR_writev
# endif
#endif
